### ISSUE TITLE
🐛 [Bug] segfault movemapgen

### ISSUE THREAD

**Issue by Thorsten42** [vmangos/core#1123]
## 🐛 Bug report

Hi,
I am using vmangos on ubuntu 20.04 and noticed that MoveMapGen crashes on exist. If compiled with tbb it crashes with

         ➜ ./MoveMapGen 0 --tile 34,46                                
        Discovering maps... found 65.
        Discovering tiles... found 2429.

        [Map 000] Creating navMesh [maxTiles=687]
        [Map 000] Building tile [34,46] (01 / 01)    
        Movemap build is complete!g to file...                                 
        [1]    86359 segmentation fault (core dumped)  ./MoveMapGen 0 --tile 34,46

and if compiled with malloc it crashes with

         ➜ ./MoveMapGen 0 --tile 34,46                   
        Discovering maps... found 65.
        Discovering tiles... found 2429.

        [Map 000] Creating navMesh [maxTiles=687]
        [Map 000] Building tile [34,46] (01 / 01)    
        Movemap build is complete!g to file...                                 
        free(): invalid pointer
        [1]    80791 abort (core dumped)  ./MoveMapGen 0 --tile 34,46

### Expected behavior

no crash

### Steps to reproduce

use ./MoveMapGen

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:   5f61e6c2cac1f3f3f5b1aff362e0db9bd902060d

OS Client: Ubuntu 20.04
OS Server: Ubuntu 20.04

### Crashlog

I used ./MoveMapGen 0 --tile 34,46 for creating the following stack trace to speed things up.

stack trace of tbb version:

 ```
➜ gdb ./MoveMapGen /tmp/core-MoveMapGen.86359.X570.1616049940 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./MoveMapGen...
[New LWP 86359]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./MoveMapGen 0 --tile 34 46'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4f6b0fe32b in ?? () from /lib/x86_64-linux-gnu/libtbbmalloc.so.2
(gdb) bt
#0  0x00007f4f6b0fe32b in ?? () from /lib/x86_64-linux-gnu/libtbbmalloc.so.2
#1  0x00007f4f6b100201 in ?? () from /lib/x86_64-linux-gnu/libtbbmalloc.so.2
#2  0x00005564c1cc6f5d in operator delete (ptr=<optimized out>) at /opt/core/src/framework/Policies/MemoryManagement.cpp:50
#3  0x00005564c1c809ea in __gnu_cxx::new_allocator<char>::deallocate (this=0x7f4f6ab33608, __p=<optimized out>) at /usr/include/c++/9/ext/new_allocator.h:119
#4  std::allocator_traits<std::allocator<char> >::deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/9/bits/alloc_traits.h:470
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x7f4f6ab33608) at /usr/include/c++/9/bits/basic_string.h:237
#6  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7f4f6ab33608) at /usr/include/c++/9/bits/basic_string.h:232
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x7f4f6ab33608, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/basic_string.h:658
#8  std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>::~pair (this=0x7f4f6ab33608, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/stl_pair.h:208
#9  __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > (this=<optimized out>, __p=0x7f4f6ab33608) at /usr/include/c++/9/ext/new_allocator.h:153
#10 std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > (__a=..., __p=0x7f4f6ab33608) at /usr/include/c++/9/bits/alloc_traits.h:497
#11 std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::_M_deallocate_node (this=<optimized out>, __n=0x7f4f6ab33600) at /usr/include/c++/9/bits/hashtable_policy.h:2102
#12 std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::_M_deallocate_nodes (this=0x7f4f6ab27e70, __n=0x7f4f6ab33b50) at /usr/include/c++/9/bits/hashtable_policy.h:2124
#13 std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear (this=this@entry=0x7f4f6ab27e70) at /usr/include/c++/9/bits/hashtable.h:2028
#14 0x00005564c1c7f207 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > >::clear (this=0x7f4f6ab27e70) at /usr/include/c++/9/bits/unordered_map.h:842
#15 VMAP::VMapManager2::~VMapManager2 (this=0x7f4f6ab27e60, __in_chrg=<optimized out>) at /opt/core/src/game/vmap/VMapManager2.cpp:45
#16 0x00005564c1c6365b in MMAP::MapBuilder::~MapBuilder (this=0x7ffd23b0e850, __in_chrg=<optimized out>) at /opt/core/contrib/mmap/src/MapBuilder.cpp:256
#17 0x00005564c1c5abfc in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/stdio.h:49
```

stack trace of malloc version:

```
 ➜ gdb ./MoveMapGen /tmp/core-MoveMapGen.80791.X570.1616049567 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./MoveMapGen...
[New LWP 80791]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./MoveMapGen 0 --tile 34 46'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f076575d859 in __GI_abort () at abort.c:79
#2  0x00007f07657c83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f07658f2285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f07657d047c in malloc_printerr (str=str@entry=0x7f07658f04ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007f07657d1cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x000055f88758398a in __gnu_cxx::new_allocator<char>::deallocate (this=0x55f888105918, __p=<optimized out>) at /usr/include/c++/9/ext/new_allocator.h:119
#6  std::allocator_traits<std::allocator<char> >::deallocate (__a=..., __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/9/bits/alloc_traits.h:470
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x55f888105918) at /usr/include/c++/9/bits/basic_string.h:237
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x55f888105918) at /usr/include/c++/9/bits/basic_string.h:232
#9  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x55f888105918, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/basic_string.h:658
#10 std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>::~pair (this=0x55f888105918, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/stl_pair.h:208
#11 __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > (this=<optimized out>, __p=0x55f888105918) at /usr/include/c++/9/ext/new_allocator.h:153
#12 std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > (__a=..., __p=0x55f888105918) at /usr/include/c++/9/bits/alloc_traits.h:497
#13 std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::_M_deallocate_node (this=<optimized out>, __n=0x55f888105910) at /usr/include/c++/9/bits/hashtable_policy.h:2102
#14 std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, true> > >::_M_deallocate_nodes (this=0x55f887b0b010, __n=0x55f888103160) at /usr/include/c++/9/bits/hashtable_policy.h:2124
#15 std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear (this=this@entry=0x55f887b0b010) at /usr/include/c++/9/bits/hashtable.h:2028
#16 0x000055f8875821a7 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, VMAP::ManagedModel, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, VMAP::ManagedModel> > >::clear (this=0x55f887b0b010) at /usr/include/c++/9/bits/unordered_map.h:842
#17 VMAP::VMapManager2::~VMapManager2 (this=0x55f887b0b000, __in_chrg=<optimized out>) at /opt/core/src/game/vmap/VMapManager2.cpp:45
#18 0x000055f8875665fb in MMAP::MapBuilder::~MapBuilder (this=0x7fffe6e32f70, __in_chrg=<optimized out>) at /opt/core/contrib/mmap/src/MapBuilder.cpp:256
#19 0x000055f88755db9c in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/stdio.h:49

```

**Comment by Thorsten42** [comment]
This issue was introduced with 03a2e10
